-- Supabase / PostgreSQL schema for E-Learning application
-- Created from python_app/app.py and python_app/api.py table usage.

CREATE TABLE IF NOT EXISTS prodi (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_prodi TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS matkul (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prodi_id INTEGER REFERENCES prodi(id) ON DELETE SET NULL,
    nama_matkul TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama TEXT NOT NULL,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    email TEXT NOT NULL,
    role TEXT NOT NULL,
    prodi_id INTEGER REFERENCES prodi(id) ON DELETE SET NULL,
    matkul_id INTEGER REFERENCES matkul(id) ON DELETE SET NULL,
    umur INTEGER,
    no_hp TEXT,
    agama TEXT,
    alamat TEXT,
    nisn TEXT,
    nidn TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS website_settings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_website TEXT,
    deskripsi TEXT,
    logo_url TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS materi (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul TEXT NOT NULL,
    file TEXT,
    matkul_id INTEGER REFERENCES matkul(id) ON DELETE SET NULL,
    dosen_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tugas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul TEXT NOT NULL,
    deskripsi TEXT,
    deadline DATE,
    file TEXT,
    matkul_id INTEGER REFERENCES matkul(id) ON DELETE SET NULL,
    dosen_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pengumpulan_tugas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tugas_id INTEGER REFERENCES tugas(id) ON DELETE CASCADE,
    mahasiswa_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    file TEXT NOT NULL,
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tugas_kumpul (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tugas_id INTEGER REFERENCES tugas(id) ON DELETE CASCADE,
    mahasiswa TEXT NOT NULL,
    file TEXT NOT NULL,
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS presensi (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL DEFAULT CURRENT_DATE,
    status TEXT NOT NULL,
    matkul_id INTEGER REFERENCES matkul(id) ON DELETE SET NULL,
    dosen_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS presensi_mahasiswa (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    presensi_id INTEGER REFERENCES presensi(id) ON DELETE CASCADE,
    mahasiswa TEXT NOT NULL,
    keterangan TEXT,
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    amount NUMERIC(12, 2) NOT NULL,
    description TEXT,
    payment_method TEXT,
    transaction_id TEXT,
    payment_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status TEXT NOT NULL DEFAULT 'pending',
    confirmed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    confirmed_date TIMESTAMPTZ,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS aktivitas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    nama TEXT NOT NULL,
    role TEXT NOT NULL,
    aktivitas TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_materi_matkul_id ON materi(matkul_id);
CREATE INDEX IF NOT EXISTS idx_tugas_matkul_id ON tugas(matkul_id);
CREATE INDEX IF NOT EXISTS idx_pengumpulan_tugas_mahasiswa_id ON pengumpulan_tugas(mahasiswa_id);
CREATE INDEX IF NOT EXISTS idx_presensi_matkul_id ON presensi(matkul_id);
CREATE INDEX IF NOT EXISTS idx_payments_student_id ON payments(student_id);
CREATE INDEX IF NOT EXISTS idx_aktivitas_user_id ON aktivitas(user_id);
