-- Supabase / PostgreSQL alter script for existing E-Learning tables.
-- Use this when tables already exist and only columns/indexes need to be added.

ALTER TABLE IF EXISTS prodi
    ADD COLUMN IF NOT EXISTS nama_prodi TEXT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE IF EXISTS matkul
    ADD COLUMN IF NOT EXISTS prodi_id INTEGER,
    ADD COLUMN IF NOT EXISTS nama_matkul TEXT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS nama TEXT,
    ADD COLUMN IF NOT EXISTS username TEXT,
    ADD COLUMN IF NOT EXISTS password TEXT,
    ADD COLUMN IF NOT EXISTS email TEXT,
    ADD COLUMN IF NOT EXISTS role TEXT,
    ADD COLUMN IF NOT EXISTS prodi_id INTEGER,
    ADD COLUMN IF NOT EXISTS matkul_id INTEGER,
    ADD COLUMN IF NOT EXISTS umur INTEGER,
    ADD COLUMN IF NOT EXISTS no_hp TEXT,
    ADD COLUMN IF NOT EXISTS agama TEXT,
    ADD COLUMN IF NOT EXISTS alamat TEXT,
    ADD COLUMN IF NOT EXISTS nisn TEXT,
    ADD COLUMN IF NOT EXISTS nidn TEXT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE IF EXISTS website_settings
    ADD COLUMN IF NOT EXISTS nama_website TEXT,
    ADD COLUMN IF NOT EXISTS deskripsi TEXT,
    ADD COLUMN IF NOT EXISTS logo_url TEXT,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE IF EXISTS materi
    ADD COLUMN IF NOT EXISTS judul TEXT,
    ADD COLUMN IF NOT EXISTS file TEXT,
    ADD COLUMN IF NOT EXISTS matkul_id INTEGER,
    ADD COLUMN IF NOT EXISTS dosen_id INTEGER,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE IF EXISTS tugas
    ADD COLUMN IF NOT EXISTS judul TEXT,
    ADD COLUMN IF NOT EXISTS deskripsi TEXT,
    ADD COLUMN IF NOT EXISTS deadline DATE,
    ADD COLUMN IF NOT EXISTS file TEXT,
    ADD COLUMN IF NOT EXISTS matkul_id INTEGER,
    ADD COLUMN IF NOT EXISTS dosen_id INTEGER,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE IF EXISTS pengumpulan_tugas
    ADD COLUMN IF NOT EXISTS tugas_id INTEGER,
    ADD COLUMN IF NOT EXISTS mahasiswa_id INTEGER,
    ADD COLUMN IF NOT EXISTS file TEXT,
    ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE IF EXISTS tugas_kumpul
    ADD COLUMN IF NOT EXISTS tugas_id INTEGER,
    ADD COLUMN IF NOT EXISTS mahasiswa TEXT,
    ADD COLUMN IF NOT EXISTS file TEXT,
    ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE IF EXISTS presensi
    ADD COLUMN IF NOT EXISTS tanggal DATE NOT NULL DEFAULT CURRENT_DATE,
    ADD COLUMN IF NOT EXISTS status TEXT,
    ADD COLUMN IF NOT EXISTS matkul_id INTEGER,
    ADD COLUMN IF NOT EXISTS dosen_id INTEGER,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE IF EXISTS presensi_mahasiswa
    ADD COLUMN IF NOT EXISTS presensi_id INTEGER,
    ADD COLUMN IF NOT EXISTS mahasiswa TEXT,
    ADD COLUMN IF NOT EXISTS keterangan TEXT,
    ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE IF EXISTS payments
    ADD COLUMN IF NOT EXISTS student_id INTEGER,
    ADD COLUMN IF NOT EXISTS amount NUMERIC(12, 2),
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS payment_method TEXT,
    ADD COLUMN IF NOT EXISTS transaction_id TEXT,
    ADD COLUMN IF NOT EXISTS payment_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending',
    ADD COLUMN IF NOT EXISTS confirmed_by INTEGER,
    ADD COLUMN IF NOT EXISTS confirmed_date TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS notes TEXT;

ALTER TABLE IF EXISTS aktivitas
    ADD COLUMN IF NOT EXISTS user_id INTEGER,
    ADD COLUMN IF NOT EXISTS nama TEXT,
    ADD COLUMN IF NOT EXISTS role TEXT,
    ADD COLUMN IF NOT EXISTS aktivitas TEXT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_materi_matkul_id ON materi(matkul_id);
CREATE INDEX IF NOT EXISTS idx_tugas_matkul_id ON tugas(matkul_id);
CREATE INDEX IF NOT EXISTS idx_pengumpulan_tugas_mahasiswa_id ON pengumpulan_tugas(mahasiswa_id);
CREATE INDEX IF NOT EXISTS idx_presensi_matkul_id ON presensi(matkul_id);
CREATE INDEX IF NOT EXISTS idx_payments_student_id ON payments(student_id);
CREATE INDEX IF NOT EXISTS idx_aktivitas_user_id ON aktivitas(user_id);
